---
- name: setup pre-requisites
  hosts: all
  become: yes
  roles:
    - install-modules
  tags: always

- name: install docker
  hosts: docker_nodes
  become: yes
  roles:
    - docker-install
  tags: always

- name: initialize docker swarm
  hosts: swarm_managers[0]
  any_errors_fatal: true
  become: yes
  roles:
    - docker-swarm-init
  tags: [ never, swarm ]

- name: add managers to the swarm
  hosts: swarm_managers[1:]
  any_errors_fatal: true
  become: yes
  roles:
    - docker-swarm-add-manager
  tags: [ never, swarm ]

- name: add workers to the swarm
  hosts: swarm_workers
  become: yes
  roles:
    - docker-swarm-add-worker
  tags: [ never, swarm ]

- name: assign labels
  hosts: docker_nodes
  become: yes
  roles:
    - docker-swarm-assign-labels
  tags: [ never, swarm_labels ]

