---
- name: Disable Docker
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items:
    - docker.service
    - containerd.service
  ignore_errors: yes
  tags: docker

- name: Uninstall Docker CE
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: absent
    update_cache: no
    force_apt_get: yes
  tags: docker

- name: Remove Docker repository
  apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian {{ ansible_lsb.codename|lower }} stable
    state: absent
  tags: docker

# Ubuntu and Debian keys are the same
- name: Remove Docker repository key
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
    state: absent
  tags: docker

# Don't remove dependencies as other services may rely on it
