---
- name: Install prerequisites
  apt:
    name:
      - python3
      - python3-apt
    state: latest
    force_apt_get: yes

- name: Install Packages
  apt:
    name:
      - python3
      - python3-apt
      - python3-docker    # docker modules
      - python3-jsondiff  # docker_stack module
      - python3-yaml      # docker_stack module
    state: latest
    update_cache: yes
    force_apt_get: yes
